import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    nav: {
      dashboard: 'Dashboard',
      families: 'Families',
      deathEvents: 'Death Events',
      analytics: 'Analytics',
      adminPortal: 'Admin Portal',
    },
    common: {
      save: 'Save',
      saving: 'Saving...',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      remove: 'Remove',
      viewAll: 'View All',
      view: 'View',
      add: 'Add',
      search: 'Search',
      notes: 'Notes',
      yes: 'Yes',
      no: 'No',
      na: '—',
      loading: 'Loading...',
      all: 'All',
      back: '← Back',
    },
    dashboard: {
      title: 'Dashboard',
      addFamily: '+ Add Family',
      recordDeath: '+ Record Death',
      enrolledFamilies: 'Enrolled Families',
      totalEvents: 'Total Events',
      totalCollected: 'Total Collected',
      outstanding: 'outstanding',
      overdueDonations: 'Overdue Donations',
      viewInAnalytics: 'View in analytics →',
      allOnTime: 'All on time',
      viewAll: 'View all →',
      recentDeathEvents: 'Recent Death Events',
      noEventsYet: 'No death events recorded yet.',
      recentlyJoined: 'Recently Joined',
      joined: 'Joined',
      members: 'members',
      member: 'member',
      paid: 'paid',
      overdue: 'overdue',
      pending: 'pending',
    },
    families: {
      title: 'Families',
      enrolledCount: 'enrolled families',
      enrolledCountSingle: 'enrolled family',
      addFamily: '+ Add Family',
      searchPlaceholder: 'Search by name...',
      name: 'Name',
      phone: 'Phone',
      address: 'Address',
      members: 'Members',
      joined: 'Joined',
      noFamilies: 'No families enrolled yet.',
      noResults: 'No families match your search.',
      loadError: 'Could not load families.',
      deleteConfirm: (name) => `Delete family "${name}"? This cannot be undone.`,
      deleteFailed: 'Failed to delete family.',
    },
    familyDetail: {
      headOfHousehold: 'Head of Household',
      joinedOn: 'Joined',
      editInfo: 'Edit Info',
      contactInfo: 'Contact & Personal Info',
      fullName: 'Full Name',
      phone: 'Phone',
      dateOfBirth: 'Date of Birth',
      dateJoined: 'Date Joined',
      address: 'Address',
      street: 'Street',
      city: 'City',
      state: 'State',
      zipCode: 'Zip Code',
      country: 'Country',
      saveChanges: 'Save Changes',
      familyMembers: 'Family Members',
      addMember: '+ Add Member',
      newMember: 'New Member',
      noMembersYet: 'No family members added yet.',
      relationship: 'Relationship',
      married: 'Married',
      covered: 'Covered',
      notCovered: 'Not Covered',
      backToFamilies: '← Back to Families',
      loadError: 'Could not load family.',
      updateFailed: 'Failed to update family.',
      addMemberFailed: 'Failed to add member.',
      updateMemberFailed: 'Failed to update member.',
      deleteMemberConfirm: (name) => `Remove "${name}" from this family?`,
      deleteMemberFailed: 'Failed to delete member.',
      firstNameRequired: 'First name is required.',
      member: 'Member',
    },
    addFamily: {
      title: 'Add New Family',
      subtitle: 'Enter the head of household information and family members',
      headOfHousehold: 'Head of Household',
      firstName: 'First Name',
      middleName: 'Middle Name',
      lastName: 'Last Name',
      phoneNumber: 'Phone Number',
      dateOfBirth: 'Date of Birth',
      dateJoined: 'Date Joined',
      address: 'Address',
      streetAddress: 'Street Address',
      city: 'City',
      state: 'State',
      zipCode: 'Zip Code',
      country: 'Country',
      familyMembers: 'Family Members',
      addMember: '+ Add Member',
      noMembersYet: 'No members added yet. Click "Add Member" to add family members.',
      saveFamily: 'Save Family',
      backToFamilies: '← Back to Families',
      validationError: 'First name and last name are required.',
      saveFailed: 'Failed to save family. Please try again.',
      relationships: ['Spouse', 'Son', 'Daughter', 'Father', 'Mother', 'Sibling', 'Other'],
      selectRelationship: 'Select...',
      married: 'Married',
      covered: 'Covered',
    },
    deathEvents: {
      title: 'Death Events',
      subtitle: 'Track deaths and donation collections',
      recordDeath: '+ Record Death',
      totalEvents: 'Total Events',
      donationsPaid: 'Donations Paid',
      donationsPending: 'Donations Pending',
      deceased: 'Deceased',
      relationship: 'Relationship',
      affectedFamily: 'Affected Family',
      dateOfDeath: 'Date of Death',
      paid: 'Paid',
      pending: 'Pending',
      allPaid: 'All paid',
      noEventsYet: 'No death events recorded yet.',
      loadError: 'Could not load death events.',
      deleteConfirm: (name) => `Delete death event for "${name}"? All payment records will also be deleted.`,
      deleteFailed: 'Failed to delete event.',
    },
    addDeathEvent: {
      title: 'Record Death',
      subtitle: 'This will automatically generate donation records for all other enrolled families',
      deathInformation: 'Death Information',
      affectedFamily: 'Affected Family (Head of Household)',
      selectFamily: 'Select a family...',
      whoPassed: 'Who Passed Away',
      headOfHousehold: 'Head of Household',
      dateOfDeath: 'Date of Death',
      notes: 'Notes',
      notesPlaceholder: 'Optional notes...',
      warningTitle: 'Donation records will be created',
      warningBody: (name) => `Saving this will generate a $50 donation record for every enrolled family except ${name}'s family.`,
      submit: 'Record Death & Generate Donations',
      backToEvents: '← Back to Death Events',
      selectFamilyError: 'Please select a family.',
      selectDateError: 'Please enter the date of death.',
      saveFailed: 'Failed to record death event. Please try again.',
      noCoveredMembers: 'No covered family members. Only the head of household is available.',
      familyMember: 'Family Member',
    },
    deathEventDetail: {
      passed: 'Passed',
      totalFamilies: 'Total Families',
      paid: 'Paid',
      pending: 'Pending',
      overdue: 'Overdue',
      totalCollected: 'Total Collected',
      notes: 'Notes',
      donationPayments: 'Donation Payments',
      searchFamily: 'Search family...',
      all: 'All',
      family: 'Family',
      phone: 'Phone',
      amount: 'Amount',
      status: 'Status',
      datePaid: 'Date Paid',
      markPaid: 'Mark Paid',
      undo: 'Undo',
      noPayments: 'No payments match your filter.',
      paidBadge: 'Paid',
      pendingBadge: 'Pending',
      overdueBadge: 'Overdue',
      backToEvents: '← Back to Death Events',
      loadError: 'Could not load event details.',
      markPaidFailed: 'Failed to mark as paid.',
      markUnpaidFailed: 'Failed to mark as unpaid.',
      viewFullProfile: 'View Full Profile',
      familyInfo: 'Family Info',
      noAddress: 'No address on file.',
      noMembers: 'No additional members.',
    },
    analytics: {
      title: 'Analytics',
      subtitle: 'Donations, events, and family payment history',
      enrolledFamilies: 'Enrolled Families',
      totalEvents: 'Total Events',
      totalCollected: 'Total Collected',
      outstanding: 'Outstanding',
      tabOverview: 'Overview',
      tabEvents: 'Events',
      tabFamilies: 'Families',
      donationsPaid: 'Donations Paid',
      donationsPending: 'Donations Pending',
      overdue: 'Overdue',
      collectionRate: 'Overall Collection Rate',
      overdueDonations: 'Overdue Donations',
      allOnTime: '✓ No overdue donations — all families are on time.',
      daysOverdue: (n) => `${n} day${n === 1 ? '' : 's'} overdue`,
      sortMostOverdue: 'Most Overdue First',
      sortLeastOverdue: 'Least Overdue First',
      forEvent: 'for',
      eventsByMonth: 'Death Events by Month',
      eventsIn: 'events in',
      noEventsYear: (year) => `No events recorded for ${year}.`,
      noEventsYet: 'No events recorded this year yet.',
      collectionRatePerEvent: 'Collection Rate per Event (Last 10)',
      collectionRateCol: 'Collection Rate',
      noEventsRecorded: 'No events recorded yet.',
      deceased: 'Deceased',
      date: 'Date',
      paidTotal: 'Paid / Total',
      familyReliability: 'Family Payment Reliability',
      allFamilies: 'All Families',
      issuesOnly: 'Issues Only',
      noIssues: 'No families with payment issues.',
      noPaymentData: 'No payment data yet.',
      family: 'Family',
      totalEventsCol: 'Total Events',
      reliability: 'Reliability',
      deathEvent: 'Death Event',
      dueDate: 'Due Date',
      amount: 'Amount',
      loadError: 'Could not load analytics.',
    },
  },

  es: {
    nav: {
      dashboard: 'Panel Principal',
      families: 'Familias',
      deathEvents: 'Fallecimientos',
      analytics: 'Análisis',
      adminPortal: 'Portal Administrativo',
    },
    common: {
      save: 'Guardar',
      saving: 'Guardando...',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      remove: 'Quitar',
      viewAll: 'Ver Todo',
      view: 'Ver',
      add: 'Agregar',
      search: 'Buscar',
      notes: 'Notas',
      yes: 'Sí',
      no: 'No',
      na: '—',
      loading: 'Cargando...',
      all: 'Todos',
      back: '← Regresar',
    },
    dashboard: {
      title: 'Panel Principal',
      addFamily: '+ Agregar Familia',
      recordDeath: '+ Registrar Fallecimiento',
      enrolledFamilies: 'Familias Inscritas',
      totalEvents: 'Total de Eventos',
      totalCollected: 'Total Recaudado',
      outstanding: 'por cobrar',
      overdueDonations: 'Donaciones Vencidas',
      viewInAnalytics: 'Ver en análisis →',
      allOnTime: 'Al día',
      viewAll: 'Ver todo →',
      recentDeathEvents: 'Fallecimientos Recientes',
      noEventsYet: 'No hay eventos registrados aún.',
      recentlyJoined: 'Inscritos Recientemente',
      joined: 'Ingresó',
      members: 'miembros',
      member: 'miembro',
      paid: 'pagado',
      overdue: 'vencido',
      pending: 'pendiente',
    },
    families: {
      title: 'Familias',
      enrolledCount: 'familias inscritas',
      enrolledCountSingle: 'familia inscrita',
      addFamily: '+ Agregar Familia',
      searchPlaceholder: 'Buscar por nombre...',
      name: 'Nombre',
      phone: 'Teléfono',
      address: 'Dirección',
      members: 'Miembros',
      joined: 'Inscrito',
      noFamilies: 'No hay familias inscritas aún.',
      noResults: 'No se encontraron familias.',
      loadError: 'No se pudieron cargar las familias.',
      deleteConfirm: (name) => `¿Eliminar la familia "${name}"? Esta acción no se puede deshacer.`,
      deleteFailed: 'No se pudo eliminar la familia.',
    },
    familyDetail: {
      headOfHousehold: 'Jefe de Familia',
      joinedOn: 'Inscrito',
      editInfo: 'Editar Info',
      contactInfo: 'Información de Contacto',
      fullName: 'Nombre Completo',
      phone: 'Teléfono',
      dateOfBirth: 'Fecha de Nacimiento',
      dateJoined: 'Fecha de Inscripción',
      address: 'Dirección',
      street: 'Calle',
      city: 'Ciudad',
      state: 'Estado',
      zipCode: 'Código Postal',
      country: 'País',
      saveChanges: 'Guardar Cambios',
      familyMembers: 'Miembros de la Familia',
      addMember: '+ Agregar Miembro',
      newMember: 'Nuevo Miembro',
      noMembersYet: 'No hay miembros agregados aún.',
      relationship: 'Parentesco',
      married: 'Casado/a',
      covered: 'Cubierto',
      notCovered: 'No Cubierto',
      backToFamilies: '← Regresar a Familias',
      loadError: 'No se pudo cargar la familia.',
      updateFailed: 'No se pudo actualizar la familia.',
      addMemberFailed: 'No se pudo agregar el miembro.',
      updateMemberFailed: 'No se pudo actualizar el miembro.',
      deleteMemberConfirm: (name) => `¿Quitar a "${name}" de esta familia?`,
      deleteMemberFailed: 'No se pudo eliminar el miembro.',
      firstNameRequired: 'El nombre es obligatorio.',
      member: 'Miembro',
    },
    addFamily: {
      title: 'Agregar Nueva Familia',
      subtitle: 'Ingrese la información del jefe de familia y sus miembros',
      headOfHousehold: 'Jefe de Familia',
      firstName: 'Nombre',
      middleName: 'Segundo Nombre',
      lastName: 'Apellido',
      phoneNumber: 'Número de Teléfono',
      dateOfBirth: 'Fecha de Nacimiento',
      dateJoined: 'Fecha de Inscripción',
      address: 'Dirección',
      streetAddress: 'Calle y Número',
      city: 'Ciudad',
      state: 'Estado',
      zipCode: 'Código Postal',
      country: 'País',
      familyMembers: 'Miembros de la Familia',
      addMember: '+ Agregar Miembro',
      noMembersYet: 'No hay miembros. Haga clic en "Agregar Miembro".',
      saveFamily: 'Guardar Familia',
      backToFamilies: '← Regresar a Familias',
      validationError: 'El nombre y apellido son obligatorios.',
      saveFailed: 'No se pudo guardar la familia. Intente de nuevo.',
      relationships: ['Cónyuge', 'Hijo', 'Hija', 'Padre', 'Madre', 'Hermano/a', 'Otro'],
      selectRelationship: 'Seleccionar...',
      married: 'Casado/a',
      covered: 'Cubierto',
    },
    deathEvents: {
      title: 'Fallecimientos',
      subtitle: 'Seguimiento de fallecimientos y donaciones',
      recordDeath: '+ Registrar Fallecimiento',
      totalEvents: 'Total de Eventos',
      donationsPaid: 'Donaciones Pagadas',
      donationsPending: 'Donaciones Pendientes',
      deceased: 'Fallecido/a',
      relationship: 'Parentesco',
      affectedFamily: 'Familia Afectada',
      dateOfDeath: 'Fecha de Fallecimiento',
      paid: 'Pagado',
      pending: 'Pendiente',
      allPaid: 'Todo pagado',
      noEventsYet: 'No hay eventos registrados aún.',
      loadError: 'No se pudieron cargar los eventos.',
      deleteConfirm: (name) => `¿Eliminar el evento de "${name}"? Todos los registros de pago también serán eliminados.`,
      deleteFailed: 'No se pudo eliminar el evento.',
    },
    addDeathEvent: {
      title: 'Registrar Fallecimiento',
      subtitle: 'Se generarán registros de donación para todas las demás familias inscritas',
      deathInformation: 'Información del Fallecimiento',
      affectedFamily: 'Familia Afectada (Jefe de Familia)',
      selectFamily: 'Seleccionar familia...',
      whoPassed: 'Quién Falleció',
      headOfHousehold: 'Jefe de Familia',
      dateOfDeath: 'Fecha de Fallecimiento',
      notes: 'Notas',
      notesPlaceholder: 'Notas opcionales...',
      warningTitle: 'Se crearán registros de donación',
      warningBody: (name) => `Al guardar se generará un registro de $50 para cada familia inscrita excepto la familia de ${name}.`,
      submit: 'Registrar Fallecimiento y Generar Donaciones',
      backToEvents: '← Regresar a Fallecimientos',
      selectFamilyError: 'Por favor seleccione una familia.',
      selectDateError: 'Por favor ingrese la fecha de fallecimiento.',
      saveFailed: 'No se pudo registrar el fallecimiento. Intente de nuevo.',
      noCoveredMembers: 'No hay miembros cubiertos. Solo el jefe de familia está disponible.',
      familyMember: 'Miembro de Familia',
    },
    deathEventDetail: {
      passed: 'Falleció',
      totalFamilies: 'Total de Familias',
      paid: 'Pagado',
      pending: 'Pendiente',
      overdue: 'Vencido',
      totalCollected: 'Total Recaudado',
      notes: 'Notas',
      donationPayments: 'Pagos de Donación',
      searchFamily: 'Buscar familia...',
      all: 'Todos',
      family: 'Familia',
      phone: 'Teléfono',
      amount: 'Monto',
      status: 'Estado',
      datePaid: 'Fecha de Pago',
      markPaid: 'Marcar Pagado',
      undo: 'Deshacer',
      noPayments: 'No hay pagos que coincidan con el filtro.',
      paidBadge: 'Pagado',
      pendingBadge: 'Pendiente',
      overdueBadge: 'Vencido',
      backToEvents: '← Regresar a Fallecimientos',
      loadError: 'No se pudieron cargar los detalles del evento.',
      markPaidFailed: 'No se pudo marcar como pagado.',
      markUnpaidFailed: 'No se pudo deshacer el pago.',
      viewFullProfile: 'Ver Perfil Completo',
      familyInfo: 'Info de Familia',
      noAddress: 'Sin dirección registrada.',
      noMembers: 'Sin miembros adicionales.',
    },
    analytics: {
      title: 'Análisis',
      subtitle: 'Donaciones, eventos e historial de pagos',
      enrolledFamilies: 'Familias Inscritas',
      totalEvents: 'Total de Eventos',
      totalCollected: 'Total Recaudado',
      outstanding: 'Por Cobrar',
      tabOverview: 'Resumen',
      tabEvents: 'Eventos',
      tabFamilies: 'Familias',
      donationsPaid: 'Donaciones Pagadas',
      donationsPending: 'Donaciones Pendientes',
      overdue: 'Vencidas',
      collectionRate: 'Tasa de Cobro General',
      overdueDonations: 'Donaciones Vencidas',
      allOnTime: '✓ Sin donaciones vencidas — todas las familias están al día.',
      daysOverdue: (n) => `${n} día${n === 1 ? '' : 's'} vencido`,
      sortMostOverdue: 'Más Vencido Primero',
      sortLeastOverdue: 'Menos Vencido Primero',
      forEvent: 'para',
      eventsByMonth: 'Fallecimientos por Mes',
      eventsIn: 'eventos en',
      noEventsYear: (year) => `No hay eventos registrados para ${year}.`,
      noEventsYet: 'No hay eventos registrados este año.',
      collectionRatePerEvent: 'Tasa de Cobro por Evento (Últimos 10)',
      collectionRateCol: 'Tasa de Cobro',
      noEventsRecorded: 'No hay eventos registrados aún.',
      deceased: 'Fallecido/a',
      date: 'Fecha',
      paidTotal: 'Pagado / Total',
      familyReliability: 'Confiabilidad de Pago por Familia',
      allFamilies: 'Todas las Familias',
      issuesOnly: 'Con Problemas',
      noIssues: 'No hay familias con problemas de pago.',
      noPaymentData: 'No hay datos de pago aún.',
      family: 'Familia',
      totalEventsCol: 'Total Eventos',
      reliability: 'Confiabilidad',
      deathEvent: 'Fallecimiento',
      dueDate: 'Fecha Límite',
      amount: 'Monto',
      loadError: 'No se pudo cargar el análisis.',
    },
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const toggle = () => setLang(l => l === 'en' ? 'es' : 'en')
  return (
    <LanguageContext.Provider value={{ lang, toggle, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
